### ISSUE TITLE
conctact cylinder error: There is no sub model part with name "ComputingContact" in model part "Structure"

### ISSUE THREAD

**Issue by luchete80** [luchete80/Kratos_tutorials#1]
When running contact cylinders:

> Traceback (most recent call last):
>   File "/home/weldform-pc/Numerico/kratos_tutorials/tests/contacting_cylinders_fixin/source/MainKratos.py", line 16, in <module>
>     analysis.Run()
>   File "/home/weldform-pc/Numerico/Kratos-9.5/bin/Release/KratosMultiphysics/analysis_stage.py", line 49, in Run
>     self.RunSolutionLoop()
>   File "/home/weldform-pc/Numerico/Kratos-9.5/bin/Release/KratosMultiphysics/ContactStructuralMechanicsApplication/adaptative_remeshing_contact_structural_mechanics_analysis.py", line 106, in RunSolutionLoop
>     self.InitializeSolutionStep()
>   File "/home/weldform-pc/Numerico/Kratos-9.5/bin/Release/KratosMultiphysics/analysis_stage.py", line 144, in InitializeSolutionStep
>     self.ApplyBoundaryConditions() #here the processes are called
>   File "/home/weldform-pc/Numerico/Kratos-9.5/bin/Release/KratosMultiphysics/analysis_stage.py", line 221, in ApplyBoundaryConditions
>     process.ExecuteInitializeSolutionStep()
>   File "/home/weldform-pc/Numerico/Kratos-9.5/bin/Release/KratosMultiphysics/ContactStructuralMechanicsApplication/alm_contact_process.py", line 222, in ExecuteInitializeSolutionStep
>     super().ExecuteInitializeSolutionStep()
>   File "/home/weldform-pc/Numerico/Kratos-9.5/bin/Release/KratosMultiphysics/ContactStructuralMechanicsApplication/search_base_process.py", line 223, in ExecuteInitializeSolutionStep
>     self.search_utility_list[key].ExecuteInitializeSolutionStep()
> RuntimeError: Error: There is no sub model part with name "ComputingContact" in model part "Structure"
> The following sub model parts are available:
> 	"Contact"
> 	"GENERIC_FixedBase"
> 	"GENERIC_Displacement_Auto1"
> 	"SkinModelPart"
> 	"CONTACT_Contact_master_Auto1"
> 	"CONTACT_Contact_slave_Auto1"
> 	"Parts_Solid_Auto1"
> 	"Parts_Solid_Auto2"
> 
> 
> 
> in kratos/sources/model_part.cpp:2416: void ModelPart::ErrorNonExistingSubModelPart(const string&) const
>    applications/ContactStructuralMechanicsApplication/custom_processes/base_contact_search_process.cpp:553: void BaseContactSearchProcess<TDim, TNumNodes, TNumNodesMaster>::UpdateMortarConditions() [with long unsigned int TDim = 3; long unsigned int TNumNodes = 3; long unsigned int TNumNodesMaster = 3]
>    applications/ContactStructuralMechanicsApplication/custom_processes/base_contact_search_process.cpp:190: void BaseContactSearchProcess<TDim, TNumNodes, TNumNodesMaster>::ExecuteInitializeSolutionStep() [with long unsigned int TDim = 3; long unsigned int TNumNodes = 3; long unsigned int TNumNodesMaster = 3]
>

**Comment by luchete80** [comment]
In search base process:

```
(base) weldform-pc@weldform:~/Numerico/Kratos-9.5/applications/ContactStructuralMechanicsApplication$ grep -r "CreateSubModelPart("
python_scripts/alm_contact_process.py:                        sub_search_model_part = self._get_process_model_part().CreateSubModelPart(sub_search_model_part_name)
python_scripts/search_base_process.py:                self.search_model_part = self.main_model_part.CreateSubModelPart("Contact")
python_scripts/search_base_process.py:            self.search_model_part = self.main_model_part.CreateSubModelPart("Contact")
python_scripts/search_base_process.py:                sub_search_model_part = self._get_process_model_part().CreateSubModelPart(sub_search_model_p
```

**Comment by luchete80** [comment]
Whereas the tests (which runs ok) are as following:
```

tests/cpp_tests/processes/test_search_process.cpp:    r_model_part.CreateSubModelPart("ComputingContact");
tests/cpp_tests/processes/test_search_process.cpp:    r_model_part.CreateSubModelPart("ComputingContact");
tests/cpp_tests/processes/test_search_process.cpp:    r_model_part.CreateSubModelPart("ComputingContact");
tests/cpp_tests/processes/test_weighted_gap.cpp:    rModelPart.CreateSubModelPart("SlaveModelPart");
tests/cpp_tests/processes/test_weighted_gap.cpp:    rModelPart.CreateSubModelPart("MasterModelPart");
tests/cpp_tests/processes/test_weighted_gap.cpp:    rModelPart.CreateSubModelPart("SlaveModelPart");
tests/cpp_tests/processes/test_weighted_gap.cpp:    rModelPart.CreateSubModelPart("MasterModelPart");
tests/cpp_tests/processes/test_weighted_gap.cpp:    rModelPart.CreateSubModelPart("SlaveModelPart");
tests/cpp_tests/processes/test_weighted_gap.cpp:    rModelPart.CreateSubModelPart("MasterModelPart");
tests/cpp_tests/processes/test_weighted_gap.cpp:    rModelPart.CreateSubModelPart("SlaveModelPart");
tests/cpp_tests/processes/test_weighted_gap.cpp:    rModelPart.CreateSubModelPart("MasterModelPart");
tests/cpp_tests/processes/test_weighted_gap.cpp:    r_model_part.CreateSubModelPart("ComputingContact");
tests/cpp_tests/processes/test_weighted_gap.cpp:    r_model_part.CreateSubModelPart("ComputingContact");
tests/cpp_tests/processes/test_weighted_gap.cpp:    r_model_part.CreateSubModelPart("ComputingContact");
tests/cpp_tests/processes/test_weighted_gap.cpp:    r_model_part.CreateSubModelPart("ComputingContact");

```
